global:
 scrape_interval: 5s
 external_labels:
   monitor: 'guidanz-monitor'
scrape_configs:
 - job_name: 'prometheus'
   static_configs:
     - targets: ['monitoring.guidanz.com:9090'] ## IP Address of the localhost